<div id="back-top" class=""><i class="fa fa-angle-double-up"></i></div>
<div class="footer-container">
	<div class="footer-static-container footer-static-container2">
		<div class="container">
			<div class="footer_introduce">
				<?php echo $this->getChildHtml("footer_static_5"); ?>
			</div>
			<div class="social-link">
				<?php echo $this->getChildHtml("social_block"); ?>
			</div>
			<div class="copyright">
				<?php  echo $this->getLayout()->createBlock("Rokanthemes\Themeoption\Block\Customcss")->setTemplate("html/copyright.phtml")->toHtml() ?>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload = function () {
		document.body.className += " preloaded";
	}
</script>
