<div class="top-content-home">
	<div class="laber-static select-element">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('laber_static')->toHtml();?>
		</div>
	</div>
	<div class="rokan-newproduct select-element">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Rokanthemes\Newproduct\Block\Newproduct')->setTemplate('Rokanthemes_Newproduct::newproduct.phtml')->toHtml();?> 
		</div>
	</div>
	<div class="banner-categoriesthumb-middle select-element">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_categoriesthumb_middle')->toHtml();?>
		</div>
	</div>
	<div class="block_newsletter">
		<div class="container">
			<div class="newsletter_home">
				<?php  echo $this->getLayout()->createBlock('Magento\Newsletter\Block\Subscribe')->setTemplate('Magento_Newsletter::subscribe.phtml')->toHtml(); ?>
			</div>	
			<div class="shipping-support-home">
				<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('shipping_support_home')->toHtml();?>
			</div>
		</div>
	</div>
</div>
