<div class="top-content-home">
	<div class="Home_Static_text">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Home_Static_text')->toHtml();?>
	</div>
	<div class="section-element categories_tab">
		<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('categories_tab_2')->toHtml();?>
	</div>
	<div class="banner-categoriesthumb-middle select-element">
		<div class="container">
			<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('banner_categoriesthumb_middle')->toHtml();?>
		</div>
	</div>
</div>
