<div id="back-top" class=""><i class="fa fa-angle-double-up"></i></div>
<div class="footer-container">
	<div class="footer-static-container">
		<div class="container">
			<div class="footer_introduce">
				<?php echo $this->getChildHtml("footer_static_3"); ?>
			</div>
		</div>
	</div>
</div>
<script>
	window.onload = function () {
		document.body.className += " preloaded";
	}
</script>
