<div class="header-container">
	<div class="header">
		<div class="for-full-withmenu">
				<div class="actions-header">	
					<div class="logo-heade"><?php echo $this->getChildHtml("logo"); ?>	</div>	
					<div class="box-actions">
						<?php echo $this->getChildHtml("topSearch"); ?>	
						<div class="wishlist hidden-xs">
							<a href="<?php echo $this->helper('Rokanthemes\Themeoption\Helper\Data')->getBaseUrl('wishlist');?>"><i class="icon-heart"></i></a>
						</div>		
						<?php echo $this->getChildHtml("minicart");?>
						<div class="header-top-setting">
							<a href="#" class="actions-top"><i class="icon-align-right"> </i></a>
							<div class="setting-container">
								<div class="container-setting-language-currency">
									<button type="button" id="btn-h-t-s-close" title="<?php echo __('Close') ?>">
										<span><?php echo __('Close') ?></span>
									</button>
									<h3><?php echo __('My account') ?></h3>
									<div class="actions dropdown options switcher-options">
										<ul class="dropdown switcher-dropdown">
											<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){?>
												<li><a href="<?php echo $this->getUrl('customer/account/login');?>"><?php echo __('Login');?></a></li>
												<li><a href="<?php echo $this->getUrl('customer/account/create');?>"><?php echo __('Sign up');?></a></li>
											<?php
											}
											else{
											?>
											<li><a href="<?php echo $this->getUrl('customer/account/index');?>"><?php echo __('My account');?></a></li>
											<li><a href="<?php echo $this->getUrl('customer/account/logout');?>"><?php echo __('Logout');?></a></li>
											<?php } ?>
										</ul>
									</div>
									<h3><?php echo __('Language') ?></h3>
									<?php echo $this->getChildHtml("store_language"); ?>
									<h3><?php echo __('Currency') ?></h3>
									<?php echo $this->getChildHtml("currency"); ?>
								</div>
							</div>
						</div>	
					</div>					
				</div>
				<?php echo $this->getChildHtml("top.navigation.sections"); ?>	
				<div class="header-bottom">
					<div class="copyright">
						<?php  echo $this->getLayout()->createBlock("Rokanthemes\Themeoption\Block\Customcss")->setTemplate("html/copyright.phtml")->toHtml() ?>
					</div>
					<div class="social-link">
						<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('social_block')->toHtml();?> 
					</div>
				</div>
		</div>
	</div>
</div>
