<?php 
	$helper = $this->helper('Rokanthemes\Instagram\Helper\Data');
?>
<div class="section widget-instagram-grid-default margin_item--<?= $block->getDataWidgetConfig('margin_grid_vertical'); ?> image_hover_effects--<?= /*@noEscape*/ $block->getDataWidgetConfig('image_hover_effects') ?>">
	<?php if($block->getDataWidgetConfig('title') != '' || $block->getDataWidgetConfig('short_description') != ''){ ?>
	<div class="elementor__header">
		<?php if($block->getDataWidgetConfig('title') != ''){ ?>
		<h3 class="elementor__headline"><?= $block->escapeHtml($block->getDataWidgetConfig('title')) ?></h3>
		<?php } ?>
		<?php if($block->getDataWidgetConfig('short_description') != ''){ ?>
		<div class="elementor__description"><?= $block->filterOutputContent($block->getDataWidgetConfig('short_description')) ?></div>
		<?php } ?>
	</div>
	<?php } ?>
	<?php $_collection = $block->getInstagramPostByStoreView(); ?>
	<?php $data_sizes = $block->getSizeThumbnail(); ?>
	<?php if ($_collection->count()) { ?>
	<div class="elementor__content widget-instagram-grid row">
	<?php $items = 0; foreach ($_collection as $_instagram) { $items ++; ?>
		<div class="col-instagram-item<?= $block->getColBootstrap(); ?>">
			<div class="elementor-instagram-item elementor__item--hover <?= $block->getDataWidgetConfig('image_format') ?><?php if ($block->getDataWidgetConfig('show_captions') == 'true') { ?> has-caption<?php } ?><?php if ($block->getDataWidgetConfig('show_instagram_icon') == 'true') { ?> has-intagram-icon<?php } ?>">
				<?php
				$width = 300;
				$height = 300;
                if(isset($data_sizes['common']['img'])){
                	$width = $data_sizes['common']['img']['width'];
                	$height = $data_sizes['common']['img']['height'];
                }
	            $aspect_ratio = $width / $height;
                ?>
				<div class="data-bgset-image-wrapper lazyload" data-bgset="<?= $helper->getMediaPath().$_instagram->getLocalMediaUrl(); ?>" data-sizes="auto" style="--aspect-ratio: <?= $aspect_ratio;?>;">
					<a class="item-link" href="<?= $_instagram->getPermalink(); ?>" target="_blank">
					</a>
				</div>
				<?php if ($block->getDataWidgetConfig('show_captions') == 'true' || $block->getDataWidgetConfig('show_instagram_icon') == 'true') { ?>
					<figure class="instagram-content">
						<?php if ($block->getDataWidgetConfig('show_instagram_icon') == 'true') { ?>
							<div class="instagram-icon"></div>
						<?php } ?>
						<?php if ($block->getDataWidgetConfig('show_captions') == 'true' && $_instagram->getCaption()) { ?>
							<figcaption><?= $_instagram->getCaption() ?></figcaption>
						<?php } ?>
					</figure>
				<?php } ?>
			</div>
		</div>
	<?php } ?>
	</div>
	<?php }else{ ?>
	<div class="message info empty">
        <div><?= $escaper->escapeHtml(__('No instagram posts were found matching your condition. No connected account. Please go to the admin > Rokanthemes > Configuration > Instagram: Settings page to connect an account.')) ?></div>
    </div>
	<?php } ?>
</div>