<?php
$helper = $this->helper('Rokanthemes\Instagram\Helper\Data');
$auto = $block->getData('auto');
$default = $block->getData('itemsDefault');
$desktop = $block->getData('itemsDesktop');
$desktop_small = $block->getData('itemsDesktopSmall');
$tablet = $block->getData('itemsTablet');
$mobile = $block->getData('itemsMobile');
$rows = $block->getData('rows');
$owl_margin = $block->getData('owl_margin');
$next_back = (1 == $block->getData('next_back')) ? 'true' : 'false';
$owl_dots = (1 == $block->getData('owl_dots')) ? 'true' : 'false';
if ($helper->getConfig('instagramsection/instagramgroup/active')) {
	$collections = $block->getInstagramPostByStoreView();
?>
	<div class="section container-rokan-instagram rokantheme-instagram">
		<?php if ($block->getData('title') || $block->getData('description')) : ?>
			<div class="rokan-title header-rokan-instagram">
				<?php if ($block->getData('title')) : ?>
					<h2 class="module-title instagram-title"><?= $block->escapeHtml($block->getData('title')) ?></h2>
				<?php endif; ?>
				<?php if ($block->getData('description')) : ?>
					<p class="rokan-description instagram-short-des"><?= $block->escapeHtml($block->getData('description')) ?></p>
				<?php endif; ?>
			</div>
		<?php endif; ?>
		<?php if ($collections->count() > 0) { ?>
			<div class="content-images-rokan-instagram">
				<div class="post-grid-widget-rokan-instagram owl-theme">
					<?php
					$i = 0;
					foreach ($collections as $val_co) {
						if ($i % $rows == 0) {
							echo '<div class="item-row">';
						}
						$i++;
					?>
						<div class="intagram-item">
							<a href="<?= $val_co->getPermalink(); ?>" target="_blank" class="<?= $block->getData('image_format') ?> <?php if ($block->getData('show_captions') == 'yes') { ?>has-caption<?php } ?> <?php if ($block->getData('show_instagram_icon') == 'yes') { ?>has-intagram-icon<?php } ?>">
								<figure>
									<div>
										<img alt="<?= $val_co->getIdInstagram(); ?>" src="<?= $helper->getMediaPath().$val_co->getLocalMediaUrl(); ?>">
									</div>
									<?php if ($block->getData('show_captions') == 'yes' && $val_co->getCaption()) { ?>
										<figcaption><?= $val_co->getCaption() ?></figcaption>
									<?php } ?>
								</figure>
							</a>
						</div>
						<?php if ($i % $rows == 0) echo "</div>"; ?>
					<?php } ?>
					<?php if ($i % $rows != 0) echo "</div>"; ?>
				</div>
			</div>
		<?php } else { ?>
			<div class="instagram-connect-error">
				<p><strong><?php echo __('Error: No connected account.'); ?></strong></p>
				<p><?php echo __('Please go to the admin > Rokanthemes > Configuration > Instagram: Settings page to connect an account.'); ?></p>
			</div>
		<?php } ?>
	</div>
	<script>
		require([
			'jquery',
			'mage/mage',
			'rokanthemes/owl'
		], function ($) {
			'use strict';

			jQuery(".post-grid-widget-rokan-instagram").owlCarousel({
				lazyLoad:true,
				autoPlay :  <?php if($auto) echo 'true'; else echo 'false'; ?>,
				items : <?php echo $default; ?>,
				itemsDesktop : [1399,<?php echo $desktop; ?>],
				itemsDesktopSmall : [1199,<?php echo $desktop_small; ?>],
				itemsTablet: [768,<?php echo $tablet; ?>],
				itemsMobile : [480,<?php echo $mobile; ?>],
				slideSpeed : 500,
				paginationSpeed : 500,
				rewindSpeed : 500,
				navigation : true,
				stopOnHover : true,
				pagination :false,
				scrollPerPage:true,
			});
		});
	</script>
<?php } ?>

